package br.edu.ufpb.wikiart;

import br.edu.ufpb.wikiart.model.Obra;import br.edu.ufpb.wikiart.service.CatalogoService;import br.edu.ufpb.wikiart.web.ApiController;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.springframework.test.web.servlet.MockMvc;import java.util.List;import static org.mockito.Mockito.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@WebMvcTest(ApiController.class) class ApiControllerTest {@Autowired MockMvc mvc;@MockitoBean CatalogoService catalogo;Obra obra=new Obra(0,"A1","Obra A","Desconhecido","Barroco","a.jpg");@BeforeEach void preparar(){when(catalogo.obras(any())).thenReturn(List.of(obra));when(catalogo.quantidade(any())).thenReturn(1);when(catalogo.fatia(any(),any(),anyInt(),anyInt())).thenReturn(List.of(obra));when(catalogo.destaques(anyInt())).thenReturn(new CatalogoService.Destaques(List.of(),List.of(),List.of()));when(catalogo.visualizar(eq(0L),anyInt())).thenReturn(new CatalogoService.Destaques(List.of(obra),List.of(new CatalogoService.Destaque(obra,1)),List.of()));when(catalogo.porId(0)).thenReturn(obra);when(catalogo.porCodigo("A1")).thenReturn(obra);when(catalogo.pertence(any(),any())).thenReturn(true);when(catalogo.periodos()).thenReturn(List.of(new CatalogoService.Periodo("barroco","Barroco",1)));}
@Test void listaEPagina()throws Exception{mvc.perform(get("/api/periodos")).andExpect(status().isOk()).andExpect(jsonPath("$[0].slug").value("barroco"));mvc.perform(get("/api/obras?size=1")).andExpect(status().isOk()).andExpect(jsonPath("$.conteudo[0].codigoAcervo").value("A1"));}
@Test void paginaPelaOrdemPedida()throws Exception{mvc.perform(get("/api/obras?ordem=titulo&page=0&size=1")).andExpect(status().isOk()).andExpect(jsonPath("$.totalPaginas").value(1));verify(catalogo).fatia(null,CatalogoService.Ordem.TITULO,0,1);mvc.perform(get("/api/obras?ordem=codigo&page=5")).andExpect(status().isOk()).andExpect(jsonPath("$.conteudo.length()").value(0));}
@Test void registraVisualizacaoEDevolveDestaques()throws Exception{mvc.perform(post("/api/obras/0/visualizacoes")).andExpect(status().isOk()).andExpect(jsonPath("$.recentes[0].codigoAcervo").value("A1")).andExpect(jsonPath("$.maisVistas[0].visualizacoes").value(1));mvc.perform(get("/api/destaques?limite=5")).andExpect(status().isOk()).andExpect(jsonPath("$.recentes.length()").value(0));mvc.perform(get("/api/destaques?limite=0")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.codigo").value("LIMITE_INVALIDO"));}
@Test void validaPaginacao()throws Exception{mvc.perform(get("/api/obras?page=-1")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.codigo").value("PAGINA_INVALIDA"));mvc.perform(get("/api/obras?size=101")).andExpect(status().isBadRequest());mvc.perform(get("/api/obras?ordem=x")).andExpect(status().isBadRequest());}
@Test void comparaEReiniciaSessao()throws Exception{mvc.perform(post("/api/buscas/comparar").contentType("application/json").content("{\"tipo\":\"CODIGO\",\"valor\":\"A1\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.medicoes.length()").value(8));mvc.perform(delete("/api/sessao")).andExpect(status().isNoContent());}
@Test void executaSoAsBuscasEscolhidas()throws Exception{mvc.perform(post("/api/buscas/comparar").contentType("application/json").content("{\"tipo\":\"ID\",\"valor\":\"0\",\"estrategias\":[\"BINARIA\",\"SEQUENCIAL\"]}")).andExpect(status().isOk()).andExpect(jsonPath("$.medicoes.length()").value(2)).andExpect(jsonPath("$.medicoes[0].tipo").value("SEQUENCIAL")).andExpect(jsonPath("$.medicoes[1].tipo").value("BINARIA")).andExpect(jsonPath("$.resumo.estrategias[3].buscas").value(1)).andExpect(jsonPath("$.resumo.estrategias[1].buscas").value(0));mvc.perform(post("/api/buscas/comparar").contentType("application/json").content("{\"tipo\":\"ID\",\"valor\":\"0\",\"estrategias\":[]}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.codigo").value("ESTRATEGIA_INVALIDA"));mvc.perform(post("/api/buscas/comparar").contentType("application/json").content("{\"tipo\":\"ID\",\"valor\":\"0\",\"estrategias\":[\"PISO\"]}")).andExpect(status().isBadRequest());}
@Test void consultasAlemDaBuscaExata()throws Exception{
mvc.perform(post("/api/buscas/consulta").contentType("application/json").content("{\"tipo\":\"PISO\",\"inicio\":5}")).andExpect(status().isOk()).andExpect(jsonPath("$.nome").value("Busca de piso")).andExpect(jsonPath("$.total").value(1)).andExpect(jsonPath("$.obras[0].codigoAcervo").value("A1"));
mvc.perform(post("/api/buscas/consulta").contentType("application/json").content("{\"tipo\":\"INTERVALO\",\"inicio\":0,\"fim\":3}")).andExpect(status().isOk()).andExpect(jsonPath("$.total").value(1));
mvc.perform(post("/api/buscas/consulta").contentType("application/json").content("{\"tipo\":\"CHAVE_SECUNDARIA\",\"artista\":\"desconhecido\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.total").value(1));
mvc.perform(post("/api/buscas/consulta").contentType("application/json").content("{\"tipo\":\"MAIOR_CHAVE\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.obras[0].id").value(0));
mvc.perform(post("/api/buscas/consulta").contentType("application/json").content("{\"tipo\":\"TETO\",\"inicio\":5}")).andExpect(status().isOk()).andExpect(jsonPath("$.total").value(0));
mvc.perform(post("/api/buscas/consulta").contentType("application/json").content("{\"tipo\":\"INTERVALO\",\"inicio\":4,\"fim\":1}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.codigo").value("INTERVALO_INVALIDO"));
mvc.perform(post("/api/buscas/consulta").contentType("application/json").content("{\"tipo\":\"CHAVE_SECUNDARIA\"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.codigo").value("ARTISTA_INVALIDO"));
mvc.perform(post("/api/buscas/consulta").contentType("application/json").content("{\"tipo\":\"BINARIA\",\"inicio\":1}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.codigo").value("CONSULTA_INVALIDA"));}
@Test void artistasEEstruturas()throws Exception{
var monet=new br.edu.ufpb.wikiart.structure.ArvoreAvlArtistas.Artista("Monet",2,3,0);
when(catalogo.artistas(0,24)).thenReturn(new CatalogoService.PaginaArtistas(List.of(monet),0,24,1,1));
when(catalogo.obrasDoArtista("Monet",0,24)).thenReturn(new CatalogoService.ObrasDoArtista(monet,List.of(obra),0,24,1,1,3,1));
when(catalogo.obrasDoArtista("Ninguem",0,24)).thenThrow(new br.edu.ufpb.wikiart.service.RecursoNaoEncontrado("ARTISTA_NAO_ENCONTRADO","Artista inexistente: Ninguem"));
var rot=new br.edu.ufpb.wikiart.structure.ArvoreAvlArtistas.Rotacoes(1,2,3,4);
when(catalogo.estruturas()).thenReturn(new CatalogoService.Estruturas(List.of(new CatalogoService.SkipListInfo("Por ID",5,3)),2,50,1,new CatalogoService.MetricasArvores(1119,12,145,11,rot,9.3,72.7,81444)));
mvc.perform(get("/api/artistas")).andExpect(status().isOk()).andExpect(jsonPath("$.conteudo[0].nome").value("Monet")).andExpect(jsonPath("$.conteudo[0].visualizacoes").value(3)).andExpect(jsonPath("$.totalElementos").value(1));
mvc.perform(get("/api/artistas?size=0")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.codigo").value("TAMANHO_INVALIDO"));
mvc.perform(get("/api/artistas?page=-1")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.codigo").value("PAGINA_INVALIDA"));
mvc.perform(get("/api/artistas/Monet/obras")).andExpect(status().isOk()).andExpect(jsonPath("$.conteudo[0].codigoAcervo").value("A1")).andExpect(jsonPath("$.comparacoes").value(3)).andExpect(jsonPath("$.profundidade").value(1));
mvc.perform(get("/api/artistas/Ninguem/obras")).andExpect(status().isNotFound()).andExpect(jsonPath("$.codigo").value("ARTISTA_NAO_ENCONTRADO"));
mvc.perform(get("/api/artistas/Monet/obras?size=101")).andExpect(status().isBadRequest());
mvc.perform(get("/api/estruturas")).andExpect(status().isOk()).andExpect(jsonPath("$.arvores.alturaAvl").value(12)).andExpect(jsonPath("$.arvores.alturaAbb").value(145)).andExpect(jsonPath("$.arvores.rotacoes.duplaDireitaEsquerda").value(4)).andExpect(jsonPath("$.skipLists[0].niveis").value(3));}
@Test void consultaPorArtistaMostraSequencialEAvl()throws Exception{
mvc.perform(post("/api/buscas/consulta").contentType("application/json").content("{\"tipo\":\"CHAVE_SECUNDARIA\",\"artista\":\"desconhecido\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.comparativo.comparacoesSequencial").value(1)).andExpect(jsonPath("$.comparativo.comparacoesAvl").value(1)).andExpect(jsonPath("$.comparativo.mesmoResultado").value(true));
mvc.perform(post("/api/buscas/consulta").contentType("application/json").content("{\"tipo\":\"CHAVE_SECUNDARIA_AVL\",\"artista\":\"desconhecido\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.total").value(1)).andExpect(jsonPath("$.comparativo").doesNotExist());
mvc.perform(post("/api/buscas/consulta").contentType("application/json").content("{\"tipo\":\"CHAVE_SECUNDARIA_AVL\"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.codigo").value("ARTISTA_INVALIDO"));}
}
