export type Obra={id:number;codigoAcervo:string;titulo:string;artista:string;estilo:string;caminhoImagem:string}
export type Periodo={slug:string;nome:string;quantidade:number}
export type Pagina={conteudo:Obra[];pagina:number;tamanho:number;totalElementos:number;totalPaginas:number}
export type Medicao={tipo:string;nome:string;encontrou:boolean;comparacoes:number;reorganizacoes:number;tempoMicros:number;cpuMicros:number|null}
export type Acumulado={tipo:string;nome:string;buscas:number;sucessos:number;comparacoes:number;reorganizacoes:number;eficaciaPercentual:number;mediaComparacoes:number;mediaTempoMicros:number;mediaCpuMicros:number|null}
export type Resumo={periodo:string|null;quantidadeObras:number;estrategias:Acumulado[]}
export type Comparacao={obra:Obra;medicoes:Medicao[];resumo:Resumo}
async function requisitar<T>(url:string,init?:RequestInit):Promise<T>{const resposta=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...init?.headers},...init});if(!resposta.ok){const erro=await resposta.json().catch(()=>({mensagem:'Falha ao acessar o servidor.'}));throw new Error(erro.mensagem??'Falha ao acessar o servidor.')}return resposta.status===204?undefined as T:resposta.json()}
export const api={periodos:()=>requisitar<Periodo[]>('/api/periodos'),obras:(periodo:string,page:number)=>requisitar<Pagina>(`/api/obras?page=${page}&size=24&ordem=id${periodo?`&periodo=${encodeURIComponent(periodo)}`:''}`),selecionar:(slug:string)=>requisitar<Resumo>(`/api/sessao/periodo/${slug||'global'}`,{method:'PUT'}),comparar:(tipo:'ID'|'CODIGO',valor:string)=>requisitar<Comparacao>('/api/buscas/comparar',{method:'POST',body:JSON.stringify({tipo,valor})}),resumo:()=>requisitar<Resumo>('/api/sessao/resumo'),reiniciar:()=>requisitar<void>('/api/sessao',{method:'DELETE'})}
